services:

  provider:
    container_name: provider
    build:
      context: ../launcher
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    environment:
      IDS_WEBHOOK_ADDRESS: http://provider:8282
      EDC_CONNECTOR_NAME: provider
      EDC_IDENTITY_DID_URL: did:web:provider-did-server:provider
      EDC_VAULT: /resources/vault/provider/provider-vault.properties
      EDC_KEYSTORE: /resources/vault/provider/provider-keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      REGISTRATION_SERVICE_API_URL: http://registration-service:8181/api
    depends_on:
      - provider-did-server
      - azurite
      - registration-service
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
    volumes:
      - ./resources:/resources

  provider-did-server:
    container_name: provider-did-server
    image: nginx
    volumes:
      - ./resources/webdid:/usr/share/nginx/html
    ports:
      - "7070:80"

  consumer-eu:
    container_name: consumer-eu
    build:
      context: ../launcher
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    environment:
      IDS_WEBHOOK_ADDRESS: http://consumer-eu:8282
      EDC_CONNECTOR_NAME: consumer-eu
      EDC_IDENTITY_DID_URL: did:web:consumer-eu-did-server:consumer-eu
      EDC_VAULT: /resources/vault/consumer-eu/consumer-eu-vault.properties
      EDC_KEYSTORE: /resources/vault/consumer-eu/consumer-eu-keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      REGISTRATION_SERVICE_API_URL: http://registration-service:8181/api
    depends_on:
      - consumer-eu-did-server
      - azurite
      - registration-service
    ports:
      - "9192:9191"
      - "8182:8181"
      - "5006:5006"
    volumes:
      - ./resources:/resources

  consumer-eu-did-server:
    container_name: consumer-eu-did-server
    image: nginx
    volumes:
      - ./resources/webdid:/usr/share/nginx/html
    ports:
      - "7071:80"

  consumer-us:
    container_name: consumer-us
    build:
      context: ../launcher
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    environment:
      IDS_WEBHOOK_ADDRESS: http://consumer-us:8282
      EDC_CONNECTOR_NAME: consumer-us
      EDC_IDENTITY_DID_URL: did:web:consumer-us-did-server:consumer-us
      EDC_VAULT: /resources/vault/consumer-us/consumer-us-vault.properties
      EDC_KEYSTORE: /resources/vault/consumer-us/consumer-us-keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      REGISTRATION_SERVICE_API_URL: http://registration-service:8181/api
    depends_on:
      - consumer-us-did-server
      - azurite
      - registration-service
    ports:
      - "9193:9191"
      - "8183:8181"
      - "5007:5007"
    volumes:
      - ./resources:/resources

  consumer-us-did-server:
    container_name: consumer-us-did-server
    image: nginx
    volumes:
      - ./resources/webdid:/usr/share/nginx/html
    ports:
      - "7072:80"

  newman:
    container_name: newman
    image: postman/newman
    entrypoint: /bin/sh
    command: deployment/seed-data.sh
    volumes:
      - ../deployment/:/deployment
    working_dir: /
    environment:
      API_KEY: ApiKeyDefaultValue
      EDC_HOST: provider
      ASSETS_STORAGE_ACCOUNT: provider-assets
    depends_on:
      consumer-eu:
        condition: service_healthy
      consumer-us:
        condition: service_healthy
      provider:
        condition: service_healthy

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    environment:
      AZURITE_ACCOUNTS: provider-assets:key1;consumer-eu-assets:key2;consumer-us-assets:key3

  registration-service:
    container_name: registration-service
    build:
      context: ../../RegistrationService/launcher
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    environment:
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
    ports:
      - "8184:8181"
      - "5008:5008"
